- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/CatvillageApplication.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/audit/DateTable.java
- 생성일, 수정일을 기록하는 date audit table 추가
- EnableJpaAuditing annotation 추가
- 컬럼 중 데이터 생성일, 수정일을 공용으로 사용하기 위한 date audit table 추가
- audit을 정상적으로 사용하기 위해서 EnableJpaAuditing 어노테이션 추가
- CatvillageApplication class에 어노테이션 적용 부분
- DateTable class
resolved #31
> feat: date audit table 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatTagPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatTagResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatTagMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
- ExceptionCode에 Breed not found와 Cat not found 에러 코드를 추가
- CatTagPostDto에 tag 길이 15로 지정하는 애너테이션 추가
- 고양이 프로필 정보 불러오는 요청시 응답에 필요한 CatResponseDto 구현
- CatController에 특정 고양이 프로필 요청에 응답하는 메서드 추가
- cat과 tag를 각각 mapper에서 dto로 변환해주도록 구현
- tag의 길이를 DB에서 15로 설계했기 때문에 catTag 입력받을 시 길이를 검증하도록 추가했습니다.
- 특정 고양이 프로필 정보 보기 기능에 필요한 클래스 및 메서드를 추가했습니다.
- CatController
- CatService
- CatMapper
- CatTagMapper
close #10
> feat: 특정 고양이 프로필 보기 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/audit/DateTable.java
- Date -> LocalDateTime 타입 변경
- Date 타입의 경우 레거시 타입이므로 사용을 지양하기 위해 변경
- 레거시 타입인 Date 타입을 사용했었기에 LocalDateTime으로 변경
- Date 타입의 경우 JPA 사용시 문제를 야기할 수 있다는 내용을 봤었기에 지양하고자 수정
- DateTable class의 필드 변수 타입 변경 내용
fixed #44
> fix: date table 변수 타입 수정

- client/src/styles/GlobalStyle.ts
- client/src/styles/Iphone11ProContainer.tsx
- Iphone 11 Pro 사이즈(375 x 812)에 맞추어 공통 레이아웃을 설정했습니다.
- Iphone11ProContainer라는 컨테이너를 생성했습니다. (아래 스크린샷 참고)
- GlobalStyle의 body 요소에 display 속성을 이용해 컨테이너를 가운데 정렬했습니다.
> style: 공통 레이아웃 설정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- user의 name 컬럼은 중복이 있으면 안되기 때문에 unique 설정 적용
- 데이터 중복이 발생하면 안되는 컬럼에 unique 설정이 빠져있었기에 추가
- user entity에 name 컬럼 unique 설정 추가 부분
fixed #49
> fix: user의 name 컬럼에 unique 적용

- client/src/styles/GlobalStyle.ts
- client/src/styles/Iphone11ProContainer.tsx
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/audit/DateTable.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCat.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatTagMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/repository/CatTagRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/repository/TagToCatRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/BreedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatTagService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/dto/MultiResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- CatTag, TagToCat repository 구현
- CatTagService에서 tag를 입력받아 저장하는 로직 구현
- 로그인 정보를 토큰에서 가져오는 로직 미구현해서 나중에 추가 필요
- 고양이 breed(품종) 관련된 로직은 확장성을 위해 BreedService로 분리
- CatController에 deleteCat 및 CatService에 removeCat 로직 구현
- removeCat 호출 시 Cat에 연결된 TagToCat리스트는 Cat 삭제 시 같이 삭제되도록 구현
- 고양이 등록하기 및 수정하기에서 입력한 tag를 저장하기 위해 tag service와 repository를 분리하였습니다.
- 고양이 수정하기, 삭제하기 요청 시 CatService에서 CatTagService를 호출하여 tag 관련된 로직을 처리합니다.
- CatTag db에 저장 시 TagToCat도 저장이 필요하기 때문에 그부분도 로직에 추가하였습니다.
- 차후에 관리자가 품종을 등록, 삭제, 수정하는 로직 구현을 위해 breed service를 분리하였습니다.
- CatService에서 saveCat의 매개변수
- TagService에서 CatTag와 TagToCat 저장 로직이 올바른지 확인
- close #12 
- close #13
> feat: 고양이 수정하기 및 삭제하기 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/BreedPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/BreedResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Breed.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/BreedMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/BreedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- CatController에 고양이 품종 관련 요청 받는 메서드 구현
- controller에서 다른 엔티티의 service를 호출하는 것은 적절치 않아 CatService 호출하고 catService가 breedService를 호출하도록 구현
- 품종 한글이름(korName), 영문이름(engName)을 DB설계에 맞춰 길이제한 20
- 고양이 품종 정보 전체보기 요청 시 필요한 클래스를 구현했습니다.
- 고양이 품종 추가하기, 삭제하기 기능은 필수 기능이 아니므로 중점적으로 보지 않아도 됩니다.
- '고양이 품종 전체보기'는 필수 기능이므로 이부분만 중점적으로 보시면 됩니다.
- resolve #14 
- resolve #17 
- resolve #18
> feat: 고양이 품종 전체보기, 추가하기, 삭제하기 기능 구현

- client/env/.env.dev
- client/env/.env.prod
- client/webpack/webpack.common.js
webpack.DefinePlugin의 인자에로 APP_API를 추가해 주었습니다
APP_API를 .env 파일에 명시하면 브라우저 환경에서 해당 환경변수를 사용할 수 있도록 기능을 추가하였습니다.
추가로, env template를 env폴더에 추가하였습니다.
```js
new webpack.DefinePlugin({
"process.env.PUBLIC_URL": JSON.stringify(process.env.PUBLIC_URL),
// 아래 줄을 추가함으로써 브라우저 환경에서 APP_API를 process.env.APP_API로 접근 가능 
"process.env.APP_API": JSON.stringify(process.env.APP_API),
"process.env.IMAGE_INLINE_SIZE_LIMIT": JSON.stringify(
process.env.IMAGE_INLINE_SIZE_LIMIT
),
}),
```
> feat: APP_API를 환경 변수에 추가 

- client/package-lock.json
- client/package.json
- client/tsconfig.json
- client/webpack/webpack.common.js
path alias 이름을 수정하고, vscode 자동완성도 가능하도록 수정하였습니다
src 폴더내의 주요 폴더들에 대해 alias를 작성하였습니다.
alias를 통해 접근하면 자동완성이 안되는 불편함을 수정하기 위해
설정 내용을 tsconfig.json로 옮기고 tsconfig-paths-webpack-plugin를 사용하여 webpack에 적용하였습니다.
/src/assets/heart.svg에 총 3가지 방법으로 접근 가능합니다.
```js
// 상대경로로 접근
import * from './../../../../assets/heart.svg'
// `@`로 접근 base url => src/
import * from '@/assets/heart.svg'
// `@Assets`로 접근 base url => src/assets
import * from '@Assets/heart.svg'
```
- tsconfig.json 변경사함
- webpack.common.js 변경사항
> fix: path alias 이름 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCat.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCatId.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- Serializable implements한 TagToCatId 클래스 생성 후 TagToCat의 Id 필드로 추가
- IdClass 애너테이션을 TagToCat에 추가
- issue #62 의 에러 일어나는 부분 주석 처리로 오류 방지 (해결 필요)
build 과정에서 발생하는 오류 해결을 위해 코드 변경
- TagToCat
- TagToCatId
resolve #63 
- 참고 블로그 : https://frogand.tistory.com/143
> fix: TagToCat PK 2개 오류 fix

- scripts/deploy.sh
- script의 build jar 경로가 달라서 수정
- jar의 경로가 달라서 실행이 안되는 문제가 발생하여 수정
- 경로
> chore: script에서 jar 경로 변경

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPatchDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPatchResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/Follow.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
- 유저 정보 보기 및 변경 API 추가
- Follow 기능 구현을 위한 entity 추가
- User entity에 Follow 및 Cat entity 연관관계 매핑
- 유저 정보 중 contentCount는 추후 feed, board 연관관계 매핑 후 구현 필요
- 회원 탈퇴 기능 추가
- 유저 정보 보기 API 추가 및 이를 위한 UserGetResponseDto 추가
- 유저 정보 수정 API 추가 및 이를 위한 UserPatchDot, UserPatchResponseDto 추가 및 UserPatchDto에 validation 적용
- 회원 탈퇴 API 추가
- 추가된 Dto의 변환을 위한 UserMapper interface에 default method 및 abstract method 추가
- Follow 기능 구현을 위한 Follow class 추가
- User class에서 Follow 및 Cat 정보를 얻기 위한 연관관계 매핑
- User class에서 Follow 및 Cat의 연관관계에 Casecade remove 적용
- 유저 정보의 name은 유니크 값이므로 유저 정보 수정 시 name의 중복 값 여부를 확인하는 로직 추가
- UserController class
- UserPatchDto class
- Follow class
- User class
- UserMapper interface
- UserService class
solved #20
solved #21
solved #68
> feat: 유저 정보 보기, 변경, 회원 탈퇴 및 follow entity 추가

- client/.eslintrc.js
- client/.prettierrc.js
- client/tsconfig.json
개발과정에서 발견된 필요한 lint관련 수정사항 들을 반영하였습니다.
1. 코드 한줄이 80줄이 넘지 않도록 .prettier.js를 수정하였습니다.
- 변경사항: [1d71caa](https://github.com/codestates-seb/seb39_main_059/commit/1d71caa27176bce4b1d75f445433e27f5474b022)
3. react/require-default-props 규칙 무시하도록 하였습니다.
- 변경사항: [c8f97b6](https://github.com/codestates-seb/seb39_main_059/commit/c8f97b629f2aca6e8d4839e3bfabfba047c8f1f0)
5. paths 속성에서 "@/*"가  앞에있어서 뒤의 자동완성에서 뒤쪽에 alias가 
적용되지 않는 문제가 있었습니다.
따라서 순서를 맨뒤에 옮겨 주었습니다.
또한 atoms, modules, template의 alias를 추가해주었습니다.
- 변경사항: [d8d9f65](https://github.com/codestates-seb/seb39_main_059/commit/d8d9f65ef47b6d672584753849185fa27d7a9a40)
> fix: lint 관련 수정사항 반영

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/CustomOAuth2UserService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/OAuthAttributes.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/SessionUser.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- 카카오 OAuth2.0 인증을 위한 코드 추가
- user의 password 컬럼 nullalbe true로 변경
- OAuth 인증으로 회원가입을 하는 유저들은 password가 따로 없기에 null로 저장되기 때문에 nullable true 필요
- CustomOAuth2UserService class
- OAuthAttributes class
- SessionUser class : 직렬화를 위한 DTO 클래스
> feat: 카카오 OAuth2 인증을 위한 코드 추가

- client/public/index.html
- client/src/styles/GlobalStyle.ts
앱 전역에서 Noto Sans KR font 적용하도록 변경하였습니다.
디자인 상으로 앱 전역에서 Noto Sans를 사용하기 때문에 
1. public/index.html에서 google font를 통해 해당 font를 불러오고 
2. body tag 내에서  Noto Sans KR font를 적용시켜 주었습니다.
- 디자인 안에서 사용되는 font-weigth인 500, 600만 불러오도록 설정해주었습니다. 만약 다른 font-weight가 사용되어야 한다면 코드 변경이 필요할 수 있습니다.
> feat: 전역에서 Noto Sans KR font 적용

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/provider/JwtTokenizer.java
- securityConfig 파일에 formLogin 및 loginProcessingUrl 추가
- JwtTokenizer에 role 하나만 넣던 로직을 여러개 받을 수 있도록 수정
- formLogin 부분이 TODO 주석 처리 되어있어서 주석 제거하고 설정해주었습니다.
- formLogin 사용 시 인증 실패, 성공에 따른 redirection은 프론트에서 처리하는것이 적절하여 로그인 요청하는 경로(loginProcessingUrl)만 설정해주었습니다.
- jwt를 생성하는 부분에서 인가 정보를 Collection으로 저장하는데 role을 하나만 넣던 것을 편의성을 위해 여러개 넣을 수 있도록 확장했습니다.
- #90
> fix: security 설정 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
- User entity에 catCount 제거
- 위 수정으로 인한 mapper 로직 및 dto 수정
- count 컬럼 중 catCount만 사용을 안하기로 했기에 제거
- 위 수정으로 인한 response dto 수정 및 mapper 로직 수정
- response dto에서 catCount를 제외한 나머지 count 컬럼들의 타입을 Integer -> Long으로 변경
- User entity에서 catCount 제외
- UserGetResponseDto class에서 count 컬럼들의 타입 변경
- UserMapper interface에서 userToUserGetResponseDto default method의 로직 수정 코드
fixed #73
> fix: User 카운트 관련 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/repository/PictureRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/PictureService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
- Picture entity 구현, feed 및 board entity 구현 후 연관관계 맵핑 필요
- Picture repository 구현, path로 데이터를 찾는 메서드 추가
- Picture service 구현, 저장 및 pictureId로 삭제하는 메서드 구현
- Picture not found 예외 추가
- Feed(냥이생활) 및 Board(집사생활)에서 공용으로 사용할 Picture(사진) Entity 추가
- Picture 저장 기능 구현
- Picture ID로 삭제하는 기능 구현
- Repository에 path로 데이터를 조회하는 메서드 추가
- Picture 조회 시 존재하지 않는 경우, 예외 처리를 위하여 PICTURE_NOT_FOUND 예외 추가
- Picture entity
- PictureRepository interface
- PictureService class
- ExceptionCode enum
solved #114
solved #115
> feat: Picture 필수 클래스 및 저장 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/Board.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardComment.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardTag.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/TagToBoard.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/TagToBoardId.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardCommentRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardTagRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/TagToBoardRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardCommentService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardTagService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/TagToBoardService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/Follow.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- Board comment(집사생활 댓글) 관련 클래스 및 인터페이스 추가
- Board tag(집사생활 태그) 관련 클래스 및 인터페이스 추가
- 집사생활 게시글에 작성할 수 있는 댓글을 구현하기 위해 수정
- 집사생활 게시글에 태그를 지정하는 기능을 구현하기 위해 수정
- 각각의 엔티티의 연관관계 매핑 코드도 추가
- Boarder와 BoarderTag를 복합키로 사용하는 TagToBoader를 위한 복합키 클래스 TagToBoaderIdId를 구현하여 사용
- User class, 연관관계 매핑
- Boarder class, 연관관계 매핑
- BoaderComment class
- BoardTag class
- TagToBoarder class
- TagToBoarderId class
> feat: Board comment 및 Board Tag 관련 클래스 추가

- client/tsconfig.json
src/components/styles에 대한 path-alias의 오타를 수정했습니다.
오타 수정
`"@Style/*": ["./src/style/*"],`
`"@Styles/*": ["./src/styles/*"],`
> fix: style폴더 path-alias 오타 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedTagDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedTagMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- User <-> Feed 양방향 연관관계에서 Cat <-> Feed 연관관계로 수정
- pictureDto 작성
- feedController에 postFeed 메서드 작성
- 냥이생활 피드에 글 작성은 고양이 프로필로만 가능하도록 정해져서 유저가 아닌 고양이 정보를 피드에서 가지고 있도록 하였습니다.
- picture는 응답과 요청에 정보가 포함되어 있기 때문에 path만 들어있는 dto를 작성하였습니다.
- 냥이생활 피드 작성에 필요한 클래스, 인터페이스 생성 및 로직 작성 했습니다.
- PictureDto
- FeedController
- FeedService
- FeedTagService
#137
> feat: 냥이생활 피드 작성하기 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatTagMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/repository/TagToCatRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatTagService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
- CatController에 postCat 구현
- CatController에 patchCat 수정
- ExceptionCode에 INVALID_USER ("Method not allowed") 추가
- UserService의 findVerifiedEmail private에서 public으로 수정
- 고양이 등록하기 시 로그인 된 유저 정보를 principal에서 가져와서 유저를 찾은 다음 cat에 같이 저장합니다.
- 고양이 수정하기 시 로그인 된 유저 정보와 처음에 고양이를 등록했던 유저 정보가 일치하지 않을 시 ExceptionCode.INVALID_USER 를 사용하여 예외 처리합니다.
- UserService의 findVerifiedEmail 은 다른 엔티티에서 로그인된 유저 정보(principal)에서 username(email 사용)로 유저의 정보를 불러와야 하기 때문에 public으로 변경합니다.
- CatService의 saveCat과 updateCat 부분
- tag가 올바르게 저장되는지
- 로그인된 유저 정보를 올바르게 사용하는지
- ExceptionCode
#62
> feat: '고양이 등록하기' 기능 구현 및 '고양이 수정하기' 기능 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/TagToBoardService.java
- 집사생활에 등록된 게시글을 수정하는 API 및 로직 구현
- 게시글 작성자와 수정 요청한 유저 정보가 다른 경우 예외 처리
- 유효성 검증 추가
- Patch의 반환 데이터는 Post의 반환 데이터를 그대로 사용하기에 동일한 Mapper method 사용으로 구현
- 집사생활에 등록된 게시글 수정을 위한 로직 추가
- 집사생활 게시글 등록 및 수정 데이터의 Title, Body 필드에 유효성 검증을 위한 어노테이션 추가
- BoardController class
- BoardPatchDto class
- BoardService class
- TagToBoardService class
resolved #108
> feat: 집사생활 게시글 수정 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
- 작성된 모든 controller에 summary, description 추가
- 기존 Swagger API 명세는 요청 별 설명이 써져있지 않아 읽기 불편하여 수정
- 모든 controller
- SwaggerConfig
> feat: Swagger API 명세에 들어갈 설명 코드 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
- 집사생활에 등록된 게시글을 삭제하는 기능 구현
- 작성자와 동일한 유저만 삭제가 가능하도록 구현
- 집사생활에 등록된 게시글을 작성자가 삭제할 수 있는 로직 추가
- BoardController class
- BoardService class
resolved #109
> feat: 집사생활 게시글 삭제 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
- List 필드들에 new ArrayList<>()를 바로 대입하던 코드 제거
- List 필드들이 생성자에서 누락되어 있던 부분 수정
- 입력을 받는데 사용되는 DTO 클래스에 초기화 코드는 필요 없으므로 제거
- 생성자에 필드가 빠져있어 대입할 수 없는 문제가 발생할 수 있으므로 수정
- 각각의 DTO 클래스의 List 필드들의 수정 부분
> fix: 집사생활 등록 및 수정시 사용되는 DTO 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardCommentResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardMultiGetResponse.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardUserCommentResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
- 집사생활에 등록된 전체 게시글을 pagination을 적용하여 불러올 수 있는 기능 구현
- 집사생활에 등록된 특정 게시글의 내용을 불러올 수 있는 기능 구현
- 집사생활에 등록된 전체 게시글을 페이지 기준으로 나누어 불러올 수 있는 로직 추가
- 집사생활에 등록된 특정 게시글의 내용을 불러올 수 있는 로직 추가
- 각각의 createdDate(생성일) 필드는 "yyyy-MM-dd HH:mm:ss" 형태로 변환하여 반환하도록 지정 (예 : 2022-09-30 04:00:00)
- 추가된 API에 대해 Swagger를 통한 API Docs 생성 시 summary 항목 추가 되도록 어노테이션 작성
- BoardController class
- BoardCommentResponseDto class
- BoardGetResponeDto class
- BoardMultiGetResponseDto class
- BoardUserCommentResponeDto class
- BoardCommentMapper interface
- BoardMapper interface
- BoardService class
resolved #105
resolved #106
> feat: 집사생활 전체 및 특정 게시글 보기 기능 구현

- .github/workflows/PR-build.yml
- .github/workflows/auto-build.yml
- server/catvillage/src/main/resources-prod/application.yml
- github actions로 CI/CD 구현한 항목에서 github secrets가 정상적으로 작동하지 않는 문제 수정
- env로 secrets를 재정의 하던 구문 주석
- 좀 더 자세히 찾아보니 github secrets를 등록 후 사용할 때 env로 재정의를 해줘야지 적용이 되는 것을 파악
- "secrets: inherit"을 사용하면 env 재정의가 없어도 동작을 한다는 내용을 찾아서 적용
- deploy-test-custom 부분
> fix: github secrets not working fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedTagDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/FollowService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/FollowFeedGetDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/FollowRepository.java
- user.service 패키지 내 FollowService 생성 및 feed에서 사용할 특정 유저의 팔로우 목록 가져오는 로직 구현
- user.repository 패키지내 FollowRepository 생성
- FeedController에 getFeeds 메서드 추가
- FeedService에 findFeeds, findfollow 메서드 추가
- 냥이생활 전체 피드 보기 요청 시 로그인한 유저가 팔로우한 유저의 고양이 정보(프로필 이미지)가 필요하여 팔로우 관련 로직을 구현했습니다.
- feed 페이지화하는 메서드와 유저가 팔로우한 고양이 리스트 반환하는 메서드 따로 작성했습니다.
- 로그인 정보가 없을 시에는 팔로우 리스트 가져오는 메서드를 호출하지 않습니다.
- FeedController의 getFeeds 부분은 컨트롤러에 너무 많은 로직이 들어가서 나중에 리팩토링이 필요합니다.
- getFeeds에 좋아요 눌렀는지 여부를 담는 로직은 빠져있어서 나중에 추가해야합니다. (TODO 주석표시 부분)
- FollowService, FollowRepository
- FeedService
- close #94
> feat: 냥이생활 전체 피드 보기 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/TagToBoardId.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCatId.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/TagToFeedId.java
- CatPostDto에 sex(성별) 부분 Pettern의 regexp 정규표현식 수정
- ~Id 클래스 필드 타입 Long으로 수정
- 고양이 등록시 성별 부분을 올바르게 입력하여도 잘못된 형식이라는 오류 발생하여 잘못된 정규표현식 수정하였습니다.
- 다대다 매핑에서 1대다 다대1 로 나눠주는 클래스에서 id를 따로 지정하지 않고 양쪽의 id 값을 합쳐서 (Serializable, IdClass 사용)사용한 부분에서 Id 값이 매핑이 안되는 오류 발생하여 Id 클래스의 필드를 실제 Id값인 Long 타입으로 수정하였습니다.
- close #159 
- close #155
> fix: post 시 복합 PK 부분 에러 fix 및 고양이 등록시 성별 에러 fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedTagRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
- FeedController에 patchFeed 메서드 구현
- FeedService에서 pictures, feed의 body 업데이트 하는 updateFeed 메서드 구현
- FeedTagService에 tag 정보 업데이트하는 updateTags 구현
- 냥이생활 피드 수정 기능에 필요한 로직들을 구현했습니다.
- picture와 tag는 기존 DB에 없던 내용이 추가되면 DB에 추가하고 있던 내용이 없다면 삭제하도록 하였습니다.
- FeedService에서 Picture와 Feed 정보가 업데이트 되는 부분
- FeedTagService에 업데이트 되는 부분
- close #96
> feat: 냥이생활 글 수정하기 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/health_check/HealthCheckController.java
- Health check시 page not found 로그를 제거하기 위하여 "/"에 get 요청시 Http status OK(200)을 반환하는 컨트롤러 구현
- 로그가 너무 자주 쌓이게 되면 로그 파일의 사이즈가 너무 커지기 때문에 제거가 필요합니다!
- "/"에 대한 Get 요청시 Http Status OK를 반환하는 간단한 로직 추가
resolved #177
> feat: health check controller 추가

- client/.eslintrc.js
- client/src/@types/user.ts
- client/src/App.tsx
- client/src/pages/Signup/Signup.tsx
- client/src/redux/actions/userAction.ts
- client/src/redux/reducers/userSlice.ts
- client/src/redux/store/index.ts
- client/src/utils/instance.ts
- ``redux-toolkit``과 비동기 처리를 위한 미들웨어인 ``redux-thunk``를 사용했습니다.
- ``redux-toolkit``을 사용하기 위해 다음과 같은 폴더와 파일을 생성했습니다.
```
redux
├── actions // 비동기 작업(ex. 서버에 요청을 보내는 작업)을 처리하는 함수를 정의합니다.
├── reducers // 액션에 따른 리듀서를 정의합니다.
└── store // 만들어진 여러 리듀서를 하나의 객체로 묶어 단일 스토어를 생성합니다.
```
``redux-toolkit``과 ``redux-thunk``를 사용해 회원가입 로직을 처리하는 방법은 다음과 같습니다.
- 유저가 회원가입에 필요한 정보를 입력하고 '회원가입' 버튼을 클릭합니다.
- ``redux/actions/userActions``에 정의되어 있는 비동기 함수에 입력한 정보를 ``argument``로 전달합니다.
- 해당 함수를 ``dispatch`` 함수의 ``argument``로 전달합니다.
```ts
// signup.tsx
dispatch(
// 회원가입 요청을 보내는 비동기 함수 signupAsync
signupAsync({
email: data.email,
password: data.password,
location: null,
name: defaultName,
profileImage: null,
}),
)
```
- 비동기 함수가 실행되고, 함수의 처리 결과에 따른 작업을 슬라이스의 ``extraReducers`` 필드에 작성합니다.
```ts
// …
```
> feat: 일반 회원가입 구현

- .github/workflows/client-auto-deploy.yml
- client/.gitignore
- client/env/.env.example
github action 실행시 환경변수 생성 단계에서 env폴더가 없어서 발생하던 오류를 해결하기 위해 다음을 변경하였습니다.
```
// .gitignore
/env/*
!/env/.env.example
```
env 폴더를 무시하는 것이 아닌 env폴더 내부의 파일을 무시하도록 하여 env폴더는 github에서 관리하도록 하였습니다.
기존 환경변수를 담은 파일이 계속 추적되는 문제를 해결하고자 #167 에서 env폴더를 제거하였고 더 이상 git으로 관리되지 않았습니다.
환경변수를 주입하기 위해 action파일에 아래와 같은 구문이 있었습니다.
```yml
#
echo "PUBLIC_URL=https://${{ env.AWS_S3_BUCKET }}">>./env/.env.prod
echo "APP_API=https://${{ env.APP_API }}">>./env/.env.prod
```
이때 env폴더가 없으므로 
`./env/.env.prod: No such file or directory`
경로 관련 문제가 발생하였습니다.
이 문제를 해결하기 위해 env폴더를 git에서 관리하도록 하여 문제를 해결하였습니다.
- 사실 env폴더를 관리하기 위해서 `env.example`을 추가하는 것이 아닌 `.gitkeep`을 추가해도 되었지만, env.example을 추가해서 template처럼 사용할 수 있도록 하였습니다.
- chore/CI-test 브랜치에 push될때 배포 액션이 트리거 되게 추가하였습니다. …
> fix: 배포 action시 환경변수 생성 문제로 실패하던 문제 해결

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/CustomOAuth2UserService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/OAuthAttributes.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
- server/catvillage/src/main/resources-prod/application.yml
- server/catvillage/src/main/resources/application-common.yml
- Kakao OAuth2.0 로그인 가능하도록 코드 수정 및 설정 변경
- Security config에 oauth2 로그인 설정을 함으로써 kakao oauth url에 인증 정보가 없더라도 접근이 가능하게 되었으므로 따로 설정을 하지 않고 해결
- kakao redirect-uri 설정을 `common`에서 `prod`로 변경 및 uri를 `.shop` 에서 `.tk`로 변경 (로컬 테스트시 `local`에 `redirect-uri: http:localhost:8080/login/oauth2/code/kakao` 설정 필요)
- CustomOAuth2UserService class의 `loadUser()` 메서드 내 `httpSession.setAttribute()` 메서드 사용 시 에러 발생으로 인해 주석처리, 해당 메서드를 사용할 필요성이 없는 것으로 보이는데 왜 넣은 것인지 의문..
- OAuthAttributes class의 `prfile` 오타 수정 및 `toEntity()` 메서드의 `picture`를 `password`에 잘 못 할당하는 로직 수정
- SecurityConfig class에 OAuth2 인증을 위한 로직 추가
- CustomOAuth2UserSerivce class
- SecurityConfig class
resolved #16
fixed #182
> fix: Kakao OAuth2 로그인 적용

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/health_check/HealthCheckController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/dto/MultiBoardResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
- swagger response data 추가
- EnableSwagger2 어노테이션 주석 처리
- Tag는 그룹화가 안되어 추가 했다가 주석 처리
- MultiBoardResponseDto class는 Swagger로 response를 정의할 때 class로 추가하기 때문에 swagger의 response class 지정을 위해 구현
- `@EnableSwagger2` 해당 어노테이션은 Swagger v3을 사용하는 경우에는 사용을 권장하지 않기에 주석 처리
- 정의한 response 데이터만 보이도록 하기 위하여 `useDefaultResponeMessages()`의 값을 `false`로 변경
- `@Tag` 어노테이션을 사용하여 컨트롤러 별 그룹화를 시도하였으나 정상적으로 동작하지 않아 일단 주석 처리
- `@ApiResponse` 어노테이션 사용 시 동일한 resposneCode를 사용하는 경우 최초 정의한 내용만 담기기 때문에 하나의 decription에 여러 내용을 작성
- 각 컨트롤러의 메서드들의 `@ApiResponse()`
- SwaggerConfig class
resolved #186
> feat: swagger response 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- FeedController에 deleteFeed 구현 (로그인 정보에서 username을 가져와서 서비스에 같이 전달합니다.)
- FeedController에 patchFeed mapping 경로에 / 빠져서 추가
- FeedServiced에 removeFeed 구현 (유저 이메일로 글을 작성한 유저의 이메일과 같은지 검증, 해당 게시글이 존재하는지 확인)
- delete-cat 로직에 유저 검증하는 로직 추가
- 냥이생활 글 삭제하기는 해당 글을 작성한 유저만 보낼 수 있는 요청이기 때문에 올바른 유저인지 확인하도록 구현하였습니다.
- 고양이 삭제하는 로직에 로그인한 유저 정보를 바탕으로 유저를 검증하는 로직이 빠져있어서 추가하였습니다.
- CatController, CatService의 유저 검증 로직 추가한 부분
- FeedService에 removeFeed 메서드
- close #97
> feat: 냥이생활 글 삭제하기 기능 구현 및 고양이 삭제시 유저 검증 로직 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
SwaggerConfig 클래스에 additionalModels에 UserMyInfoDto 적용
Swagger API Docs 페이지에서 /users/my-info 요청에 관한 body 정보가 없어 SwaggerConfig에 코드 추가했습니다.
> fix: Swagger API docs에 UserMyInfoDto 적용 안되는 문제 fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
- get-feed에 feed 마다 이미지 list 길이 확인하여 1개라도 있을 경우에만 가져오도록 수정
- createFeed 에 요청한 user 검증 로직 추가
- createFeed에서 pictureService의 createPicture 요청 시 picture에 feed 저장하여 파라미터로 전달
- FeedTagService createTags에 feedTag 리스트 생성하여 값 담아 전달
- FeedMapper에 pictures 가 null 이 아닐 경우만 picture 리스트 저장하도록 변경
- 요청시 이미지 list 길이 확인 없이 첫번째 인덱스(0번) 가져오려고 해서 이미지 없을 시 ArrayOutOfIndex 오류가 발생할 수 있어 연결된 Picture가 1개라도 있는지 확인하도록 수정하였습니다.
- 냥이생활 피드 요청시 로그인한 유저가 요청으로 보낸 catId를 소유한 유저인지 검증하는 로직이 없어서 추가하였습니다.
- 냥이생활 피드작성하기와 수정하기 기능에 DB에 잘못 저장되거나 응답이 에러로 와서 수정하여 해결했습니다.
- 테스트 진행하면서 문제없는지 확인 필요
close #185
> fix: 냥이생활 피드 작성하기 및 수정하기 기능 bug fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatTagService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
- CatMapper.catPostDtoToCat에 image 매핑 코드 추가
- Cat Builder 생성자에 매개변수 image 추가
- CatTagService를 CatService에 주입하던 것을 CatController에 주입하도록 수정
- patch-cat 에서 catId를 서비스에 같이 전달하여 findVerifiedCat 호출시 매개변수로 사용
- patch-user 에서 userId를 서비스에 같이 전달하여 findVerifiedUser 호출시 매개변수로 사용
- post-cat 요청 시 image 정보 누락되어 null로 들어가는 오류 있어서 수정했습니다.
- 같은 도메인의 서비스는 컨트롤러에서 주입하는것이 적절하다 판단하여 CatTagService를 CatController에 주입하도록 수정했습니다.
- patch-cat, patch-user 에서 Id와 수정할정보를 따로 받아서 cat을 service에 전달하는데 수정할 정보에 id를 넣지 않은 채로 전달하여 id null 값이라 NullPointException 발생하여 수정했습니다. 
- CatController, CatService
- UserController, UserService
close #173
> fix: 고양이 등록하기, 수정하기 및 유저 정보 수정하기 기능 오류 fix

- client/src/layout/MainLayout.tsx
- client/src/layout/PhoneLayout.tsx
- client/src/routes/AppRoutes.tsx
- client/src/routes/board.routes.tsx
- client/src/routes/feed.routes.tsx
- client/src/routes/index.ts
- client/src/routes/main.routes.tsx
main 페이지인 /집사생활, /냥이생활에 대응하는 layout을 제작하였습니다.
집사생활 페이지와 냥이생활 페이지는 다음과 같이
- 상단의 화면 전환 nav 바
- 하단의 tap 바
를 동일하게 공유합니다.
때문에 새로운 레이아웃을 작성하여 라우팅하여 화면 전환시 nav, tap바는 유지하면서 세부 화면만 로딩하는 것이 좋다고 판단하였습니다.
layout을 다음과 같이 작성하고 feeds와 boards에 사용할 라우터 객체를 만들어 주었습니다.
```jsx
// src/layout/MainLayout.tsx
export const MainLayout = () => {
return (
<>
/<Nav />
/<Outlet />
/<TapBar />
</>
)
}
```
```jsx
// src/routes/main.routes.tsx
export const mainRoutes: RouteObject = {
path: '',
element: <MainLayout />,
children: [
{ index: true, element: <Navigate to={FEED_PATH} /> },
{ path: FEED_PATH, element: <Feeds /> },
{ path: BOARD_PATH, element: <Boards /> },
],
}
```
최종적으로 appRouter에 추가해 주었습니다.
```jsx
// src/routes/AppRoutes.tsx
const appRoutes: RouteObject = {
path: '/',
element: <DashBoard />,
children: [ …
```
> Feat: main페이지 layout제작

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/refreshToken/RefreshTokenRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/service/AuthService.java
- accessToken 및 refreshToken을 받은 후 해당 토큰들을 폐기하는 동작을 수행하는 logout API 추가
- 입력 받은 accessToken으로 더 이상 로그인 하지 못 하게 하는 기능은 추후 개발로 미뤄져 있는 상태
- 현재 Refresh Token만 삭제하는 로직 수행
- logout을 위한 로직 추가
- 입력 받은 refresh token이 존재하지 않는 경우 에러 반환
- 존재하는 refresh token인 경우, 해당 refresh token을 삭제
resolved #19
> feat: logout 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
- 직접 구현한 logout을 사용하므로 security에서 제공하는 logout 비활성화
- 해당 문제로 logout이 안되던 문제 발생
- security에서 기본적으로 제공되는 logout 기능과 충돌이 발생하였기에 이를 해결하기 위함
- security config에서 logout disable 처리
> fix: security 제공 logout 비활성화

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/config/BusinessLogicExceptionHandler.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/dto/ErrorResponse.java
- business logic exception 발생 시, 해당 Error status code 및 message를 반환하도록 하는 handler 추가
- 현재 business logic exception에 대해서만 핸들링을 하고 있으며, 인증 관련 예외는 추후에 추가 필요
- 예외 발생 시, 어떤 이유로 발생 했는지를 프론트엔드에 전달하기 위한 예외 핸들러 추가
- `@RestControllerAdvice` 어노테이션을 사용하여 RestController에서 발생하는 예외를 핸들링
- `@ExceptionHandler` 어노테이션을 사용하여 어떠한 예외를 처리할지 지정하여 핸들링
- 인증 관련 예외는 controller 단에서 발생하는게 아닌 filter 단에서 발생하므로 해당 방법으로 핸들링 불가
- 인증 관련 예외는 `AuthenticationEntryPoint` interface를 상속 받아서 처리할 수 있는 것으로 파악
- 시도는 해보았으나 잘 안되어 이후에 추가 구현 필요 (현 수정에 코드 반영 X)
- BusinessLogicExceptionHandler class : 실질적으로 예외를 핸들링하는 클래스
- ErrorResponse class : 예외 발생 시 해당 내용을 전달하는 DTO 역할의 클래스
resolved #72
> feat: business logic exception handler 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
- 집사생활 게시글 등록 및 수정 시 발생할 수 있는 NullPointerException 예방
- 집사생활 게시글 수정 시 title과 body의 수정 로직이 누락된 부분 추가
- 집사생활 특정 게시글 조회 시, 댓글 출력에 필요한 데이터로 변경 (이전 코드는 My page에서 나와야 하는 데이터)
- 위 댓글 출력에 필요한 데이터에 댓글 작성자의 유저 페이지 링크 추가
- 등록 및 수정 시 body에 tags 및 pictures가 넘어오지 않으면 NullPointException이 발생하기 때문에 이를 예방하고자 tags, pictures에 `new ArrayList<>();`를 할당, 데이터 정상적으로 들어오는 것 확인 완료
- 수정 시 title과 body를 수정하는 로직이 빠져있어서 수정
- 특정 게시글 조회 시 나오는 댓글 데이터가 부적절하여 변경
- BoardService class : 게시글 수정 로직에서 title, body 추가된 코드
- BoardController class : 댓글 응답으로 `BoardUserCommentResponseDto`에서 `BoardCommentResponseDto`로 변경된 점
> fix: 집사생활 등록 및 수정 시 에러 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatTagPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
- CatPostDto에 image 길이제한 max 500으로 수정
- CatPostDto와 CatTagPostDto에 변수 별로 설명, 예시 작성
- 고양이 등록시 image 경로 길이제한이 50으로 되어 있어서 DB설계에 맞추어 500으로 늘렸습니다.
- 고양이 등록은 프론트엔드 개발시 헷갈릴 수 있어서 변수에 설명과 제한, 예시를 작성하였습니다.
- CatPostDto
- CatTagPostDto
- close #224
> feat: Swagger에 Post-Cat 요청 dto에 대한 설명 작성

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardTag.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/CatTag.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/CatInfo.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/Disease.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedTag.java
- BoardTag, CatTag, FeedTag 의 tagName 칼럼을 Unique 값으로 설정하여 unique true 로 코드 변경
- Disease의 name 에 unique 속성 추가
- CatInfo의 korName에 unique 속성 추가
- 테그 이름은 고유하기 때문에 DB에서 Unique 속성 부여하여 코드에서도 동일하게 적용했습니다.
- unique true 부분
> fix: tagName 칼럼에 Unique 속성 추가

- client/src/@types/feed.ts
- client/src/pages/Feed/Feeds/Feeds.style.ts
- client/src/pages/Feed/Feeds/Feeds.tsx
- client/src/redux/actions/FeedsAction.ts
- client/src/redux/reducers/FeedSlice.ts
- client/src/redux/store/index.ts
- 더미데이터를 생성해 냥이생활 전체 피드 페이지에 렌더링했습니다.
- 이후 실제로 서버에 데이터를 요청해 페이지에 렌더링했습니다.
- 서버에 데이터를 요청하고 이를 state로 관리하기 위해 redux 폴더에 ``feedsActions.ts``와 ``feedsSlice.ts``를 생성했습니다.
- 서버에 전체 피드 데이터를 불러오는 함수 ``getFeedsAsync``를 정의했습니다.
- 데이터를 요청할 때 page와 size를 쿼리스트링으로 필수로 전달하도록 구현되어있습니다.
- 따라서 현재 state의 page와 size를 가져오기 위해 ``thunkAPI.getState``를 사용했습니다.
```ts
// src/redux/actions/FeedsAction.ts
export const getFeedsAsync = createAsyncThunk<
Feeds,
undefined,
CreateAsyncThunkTypes
>('feeds/getFeedsAsync', async (_, thunkAPI) => {
try {
// thunkAPI.getState()로 현재 state값을 조회할 수 있습니다.
// feedsSlice.ts 파일에 정의되어있는 feeds라는 슬라이스에 접근해 state를 조회하고, 그 중 page와 pazeSize를 가져와 변수로 사용합니다.
const { page, pageSize } = thunkAPI.getState().feeds
// axios를 사용하면 데이터는 response.data와 같이 data라는 객체에 저장되기 때문에 
// 구조 분해 할당을 통해 …
```
> [FE] 냥이생활 전체 피드 페이지 데이터 불러오는 로직 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedCommentGetDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedCommentMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- get-feed. get-feeds 요청에 응답 데이터 수정(viewCount 제거, name 추가, profileImage 추가)
- get-feed, get-feeds 요청에 like 담도록 로직 변경
- 피드 페이지에서 조회수 데이터는 사용하지 않아 피드 응답데이터에서 제거했습니다.
- 피드 페이지에 작성자 정보가 필요하여 작성자 이름과 프로필 이미지 정보 추가했습니다.
- 피드 가져오기 요청 시 로그인된 상태라면 좋아요 눌렀는지 여부가 필요하여 코드 추가했습니다.
- feedController에 getFeed, getFeeds 로직 올바른지
- feedMapper
- feed 반환 dto 들
close #236
> fix: 냥이생활 특정 피드 보기에 변수 수정 및 피드 반환 데이터에 좋아요 데이터 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/CorsConfig.java
- `http://localhost:3000`에 대한 cors origin 허용
- 프론트엔드 로컬 테스트 환경 구축을 위한 cors origin 추가
> fix: local test를 위한 cors origin 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
- server/catvillage/src/main/resources/application-common.yml
- S3 버킷 이름 수정
- spring에 MultipartFile에 용량제한 기본값인 1MB로 되어있어서 5MB로 설정 변경
- S3 버킷에 온점 들어가면 https 적용이 정상적으로 되지 않아 브라우저에 사진 렌더링 실패하는 문제가 있어 버킷 새로 생성
- 버킷 이름 바뀌면서 버킷 이름 환경변수 수정
- 이미지 업로드 시 1M 이상이면 FileSizeLimitExceededException 파일 사이즈 제한 초과 예외 발생 하여 MultipartFile 용량제한 5MB로 변경, 서비스 로직에서 검증할 때는 4MB
- application.yml
- S3UploadService
#241
> fix: 이미지 저장용 S3 버킷 이동으로 버킷 이름 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
- profileImage가 null로 들어올 경우 기본 프로필 이미지로 저장
- 프로필 이미지가 null로 들어올 경우 페이지에서 깨지기 때문에 S3에 업로드한 기본 프로필 이미지로 저장하게끔 수정했습니다.
> fix: 유저 정보 변경 시 기본 프로필 이미지 설정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- 이미지 업데이트 하는 부분에서 추가된 이미지는 Picture 생성하여 feed, path 할당 후 PictureSerivce에 저장하는 메서드 호출하도록 변경
- picture 업데이트 시 feed가 할당되지 않은 상태로 저장되어 picture에 feed가 null 값으로 저장되었습니다.
- 그래서 get-feed 요청 시 picture가 누락된 상태로 전달되었습니다.
- picture에 feed 할당 후 저장하도록 변경했습니다.
- 로컬에서 정상적으로 되는지 테스트도 완료했습니다.
> fix: 냥이생활 피드 수정하기 시 사진 저장되지 않는 오류 fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
- 집사생활 조회 mapper 동작에서 pictures에 `isEmpty()` 대신 null 체크로 변경
- `isEmpty()`의 경우 null을 만나면 `NullPointerException(NPE)`이 발생하기 때문에 null 체크로 변경
> fix: 집사생활 조회 시 사진 로직 수정

- client/src/layout/DashBoard.tsx
- client/src/layout/PhoneLayout.tsx
- client/src/layout/PresentLayout.tsx
- client/src/routes/AppRoutes.tsx
개발 과정에서 사용했던 레이아웃인 DsahBoard 대신 PresentLayout을 제작하고 대체하였습니다.
boxshadow을 줘 화면의 경계를 나타내고 화면 가운데 정렬을 하였습니다
> feat: app layout을 발표용 layout으로 변경

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
- catMapper에 catPostDtoToCat에 기본이미지 자동 저장 로직 추가
- 고양이 등록, 수정 요청 시 프로필 이미지가 null 또는 빈 문자열로 입력될 경우 이미지 서버에 저장된 기본 이미지로 저장
- 유저가 고양이 프로필에 프로필 이미지를 등록하지 않을 경우 디폴트 이미지로 자동 설정하도록 구현했습니다.
- catPostDtoToCat
> feat: 고양이 프로필 기본 이미지 자동 할당

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/comment/BoardCommentResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardCommentMapper.java
- 사용하지 않는 생성일 데이터 제거
- 누락되었던 profileImage 데이터 추가
- 집사생활 댓글 표현 시 필요한 데이터 누락으로 추가
- 집사생활 댓글 표현 시 필요 없는 데이터가 존재하여 제거
- BoardCommentResponseDto class
- profileImage 항목 추가
- createdDate 제거
- BoardCommentMapper interface
- 추가 및 제거된 항목에 대한 로직이 올바른지
fixed #265
> fix: 집사생활 댓글 반환 데이터 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatSimpleDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedSimpleDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
- user 엔티티에 representCat 추가 및 Cat에 1:1 단방향 매핑
- user 엔티티에 provider 추가
- CatSimpleDto 생성 및 매퍼에 매핑 로직 구현
- FeedSimpleDto 생성 및 매퍼에 매핑 로직 구현
- DB에 칼럼 추가로 코드에 반영했습니다.
- provider는 oauth 회원 식별용입니다.
- 유저 프로필 페이지에 필요한 dto 생성했습니다.
- User 엔티티에 추가된 부분
> fix: user 테이블 칼럼 추가로 엔티티에 변수 추가 및 유저 프로필 페이지에 필요한 dto 생성

- client/src/@types/feed.ts
- client/src/components/template/Comments/Comments.tsx
- client/src/components/template/FeedDetail/FeedDetail.tsx
- client/src/pages/Feed/FeedDetail/FeedDetail.tsx
- 냥이생활의 댓글 응답 데이터가``catId`` 또는 ``userId`` 둘 중 하나만 전달받기 때문에 옵셔널 타입으로 지정해주었습니다.
- ``feedDetail`` state를 ``CommentsView``에서도 사용하기 위해 관련 로직을 상위 컴포넌트인 ``FeedDetail`` 페이지로 옮겼습니다.
- 페이지에서 state를 받아와 각각의 컴포넌트에 props로 전달합니다.
- 응답 데이터에 따라 댓글을 렌더링하도록 구현했습니다.
- ``Comments``(댓글) 템플릿이 냥이생활과 집사생활에 동일하게 적용되기 때문에 템플릿을 재사용하면 좋겠다고 생각했습니다.
- 다만 냥이생활과 집사생활의 댓글 응답 데이터의 필드명이 조금씩 달라 (ex. ``feedCommentId``와 ``boardCommentId``), 현재는 냥이생활 응답 데이터를 기준으로 렌더링하도록 구현되어있습니다. 이후 집사생활에서 댓글 데이터를 처리할 때 이 부분을 어떻게 활용할 수 있을지 의견 주시면 감사하겠습니다.
> [FE] 댓글 리팩토링

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
- FileUploadController에 이미지 삭제 요청 받을 deleteFile 메서드 구현
- S3UploadService에 이미지 삭제 로직 구현
- 사용자가 파일에서 이미지 선택하여 업로드시 바로 S3 이미지 서버에 저장되지만 사용자가 이미지를 게시하지 않을 경우 사용하지 않는 이미지가 그대로 S3에 남아 문제 발생할 수 있어 사용하지 않은 이미지는 삭제하는 API 구현했습니다.
- /images/delete 엔드포인트로 이미지 경로 body에 담아서 보내면 이미지가 s3에서 삭제됩니다.
- 삭제 시 SDK 지원 메서드인 deleteObject에 S3의 버킷과 키를 입력하여 삭제합니다.
- 한글이 포함된 URL은 인코딩되어 있어 삭제되지 않는 오류 발생하여 url을 디코딩하여 String으로 변환후 삭제 요청합니다.
- 로직이 올바른지
- 엔드포인트가 적절한지
close #280
> feat: s3 파일 삭제 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
- userService에 addContentCount, deleteContentCount 로직 구현
- feedService에 create, delete 로직에 contentCount 업데이트 로직 추가
- boardController에 create,delete 로직에 contentCount 업데이트 로직 추가
- 유저 테이블과 유저 프로필 페이지에 게시글 수가 있지만 실제로 count 하는 로직이 없어 contentCount가 모두 0으로 저장되어 있어 냥이생활또는 집사생활에 글 작성, 삭제 시 contentCount가 업데이트 되도록 구현했습니다.
- feed는 feedService에 UserService가 주입되어 있어 서비스단에서 호출하도록 구현했습니다.
- board는 boardController에 UserService가 주입되어 있어 컨트롤러단에서 호출하도록 구현했습니다.
- 로직이 적절한지
- 빠진 부분은 없는지
close #272
> feat: 게시글 작성 수 count 로직 구현

- client/src/components/modules/FormTextInput/FormTextInput.tsx
- client/src/components/template/FeedForm/FeedForm.tsx
- client/src/pages/Feed/NewFeed/NewFeed.tsx
- client/src/pages/Page404/index.tsx
- 냥이생활 피드 작성 페이지의 이미지 업로드 컴포넌를 불러와 이미지 미리보기 기능이 동작하도록 했습니다.
- 냥이생활 피드 작성 페이지에서 로그인 체크 유무 로직을 수정했습니다.
> fix: 냥이생활 피드 작성 페이지 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- FeedController에 API 추가
- FeedService에 특정유저의 모든 고양이 프로필로 작성한 피드 가져오는 로직 구현
- FeedRepository에 findByCat 추가
- SwaggerConfig에 FeedSimpleDto 추가
- 유저 프로필 페이지에 들어갈 특정 유저가 작성한 피드정보 불러오는 API 구현했습니다.
- 엔드포인트는 /냥이생활/users/{users-id} 입니다.
- 특정 유저의 모든 고양이를 조회하여고 고양이로 작성한 모든 피드를 조회합니다.
- 피드 정보에 대표사진 1장과 클릭했을 때 페이지 넘어가는데 필요한 id 값만 반환합니다.
- FeedService
- FeedController
- FeedRepository
close #274
> feat: 특정 유저가 작성한 피드 불러오는 API 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
- 집사생활 전체 게시글 조회 시 index out of bound 에러 수정
- index out of bound 발생하며 조회 안되는 버그 수정
- picture의 size가 '0'인 경우는 확인을 안하는 바람에 발생하던 문제 수정
> fix: 집사생활 전체 게시글 조회 버그 수정

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
- server/catvillage/src/main/resources-prod/application.yml
- server/catvillage/src/main/resources/application-common.yml
- Feed 작성 또는 수정 시 picture 리스트가 null 또는 empty(길이0)인지 확인하도록 유효성 검증 추가
- pictureDto에 이미지 경로가 http 또는 https로 시작하는지 확인하는 유효성 검증 추가
- feedTagService에 feedTag가 isEmpty인지 체크하는 부분 앞에 null 인지 먼저 체크하도록 수정
- BoardPostDto 및 BoardPatchDto에 tags null 또는 empty인지 확인, pictures @Valid 추가
- 모든 yml 설정 파일에서 show-sql을 false로 수정
- 설계 상 냥이생활 피드는 사진이 1장 이상이어야 하기 때문에 비어있으면 안되서 유효성 검증 로직을 추가했습니다.
- 이미지에 url 경로가 아닌 다른 경로가 들어올 수 있어 http or https 로 시작하는 문자열인지 확인하도록 검증 코드 추가했습니다.
- feed 작성 시 tag는 nullable인데 feedService 로직에서 null 일 경우 feedTag.isEmpty 메서드 호출 부분에서 NPE가 발생하여 null인지 먼저 확인하도록 수졍하였고 에러 나지 않는지 포스트맨으로 확인 완료했습니다.
- DTO 내의 DTO 리스트의 유효성 검증이 정상적으로 이루어지지 않아 호출하는 부분에 @Valid 애너테이션 추가하여 해결했습니다.
- sql log가 너무 많아 가독성이 떨어지고 log 파일 용량 문제가 발생하여 sql문은 log에 남기지 않도록 설정을 변경했습니다.(이 부분에 대한 피드백 부탁드립니다.)
- 유효성 검증 애너테이션이 적절한지
- …
> fix: picture 및 tag의 유효성 검증 추가, tag NPE 버그 fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java
- post-cat 요청 로직에 user에 representCat 이 지정되어 있지 않을 경우 자동으로 요청으로 보낸 고양이를 user의 representCat으로 설정하도록 로직 구현
- UserService에 updateRepresentCat 메서드 구현
- 대표고양이 지정 API 구현
- 고양이 최초 등록 시 자동으로 대표고양이로 설정하도록 설계하여서 설계에 맞춰 post-cat 로직에 코드 추가하였습니다.
- representCat은 User에 있는 칼럼이기 때문에 UserService에 대표고양이를 업데이트하는 메서드를 구현했습니다.
- 대표고양이를 고양이 프로필에서 버튼 클릭으로 지정할 수 있도록 설정하였기 때문에 API 구현했습니다. 엔드포인트는` /cats/{cats-id}/대표 `입니다.
- 대표고양이 지정은 delete 요청은 적절하지 않다고 생각하여 post 요청만 구현했습니다.
- 추가된 코드가 매우 간단하기 때문에 빠뜨린 부분이나 잘못된 부분이 없는지만 체크 부탁드립니다 :)
- close #301 
- close #277
> feat: 대표 고양이 설정 API 구현

- client/src/pages/Feed/Feeds/Feeds.tsx
- client/src/pages/Feed/NewFeed/NewFeed.tsx
- client/src/pages/Login/Login.tsx
- client/src/pages/Signup/Signup.tsx
- client/src/redux/actions/FeedsAction.ts
- client/src/redux/reducers/FeedsSlice.ts
- 냥이생활 좋아요 추가 기능을 구현했습니다.
- 구현하는 중에 에러를 발견해 @leejuhanKr 님이 이슈를 등록하고 해결해주셨습니다.
- 에러 해결 과정은 #303 이슈에서 자세히 확인할 수 있습니다.
- 냥이생활 좋아요 취소 기능을 구현했습니다.
- 좋아요 추가/취소 기능을 냥이생활 전체 피드에 적용했습니다.
- 로그인/회원가입 페이지에 각각의 페이지로 이동하는 버튼이 있습니다.
(로그인 페이지 -> 회원가입 페이지로 이동하는 버튼 / 회원가입 페이지 -> 로그인 페이지로 이동하는 버튼)
- ``Link`` 컴포넌트를 사용해 해당 페이지로 이동하도록 했습니다.
#303
#208
> [FE] 냥이생활 좋아요 추가/취소 기능 구현

- server/catvillage/src/main/resources-prod/application.yml
- 배포용에서는 SQL 로그가 출력되지 않도록 수정
- SQL 로그가 너무 쌓이던 문제 수정을 위해 로그 설정 주석
- `show-sql` 설정이 아닌 주석 처리한 설정으로도 sql 로그를 설정할 수 있음을 확인해주시면 될 것 같습니다!
> fix: 배포용에선 SQL 로그 제거

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/controller/CatInfoController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoPostDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoSimpleDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/DiseaseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/CatInfo.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/mapper/CatInfoMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/service/CatInfoService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
- DiseaseDto 구현 및 질병 이름 담을 name 변수 필드에 추가
- CatInfoPostDto에 DiseaseDto List 추가
- CatInfoController 및 Service에 모든 품종 정보 가져오기 API 구현
- SwaggerConfig에 구현한 DTO 추가
- CatInfoController 및 Service에 특정 품종 정보 가져오기 API 구현
- CatInfo 엔티티에 Picture 추가
- CatInfoPostDto에 picture 및 showCatInfo 변수 추가
- 고양이 품종 정보 작성 요청 시 질병 정보를 담는 변수가 없어 질병 dto 작성하였고 리스트로 가지고 있도록 작성하였습니다.
- 고양이 프로필 등록 페이지에 모든 고양이 품종 정보가 필요하여 API 구현했습니다.
- 특정 고양이 품종 정보 페이지에 필요한 특정 품종 정보 보는 API 구현했습니다. CatInfo Id를 통해 조회합니다.
- 설계에 맞춰 CatInfo 테이블에 PICTURE 칼럼이 추가되어서 CatInfo 엔티티에도 적용했습니다.
- 차후에 관리자 모드(인가) 등 확장성을 고려하여 고양이 품종정보 페이지에 보여지는지 여부(showCatInfo)를 postDto에 추가하였습니다.
- update 요청 구현 시도 showCatInfo를 받도록 구현 필요합니다.
- 조회 로직이 잘못되진 않았는지
- 변수 명, 메서드 명이 모호하지 않고 적절한지
- CatInfo 엔티티에 변수 추가한 부분
- DTO, mapper에 누락된 변수는 없는지
- close #207 
- close #314 
- close …
> feat: 고양이 품종 정보 조회(전체, 특정) API 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
- PictureDto에 picture 정규표현식 수정
- 이전에 Picture에 유효성 검증하는 정규표현식이 잘못되어 post-집사생활에서 400, bad request 에러가 발생하여 수정했습니다.
> fix: picture에 유효성검증 정규표현식 버그 fix

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
- 냥이생활의 특정 피드 및 전체 피드 조회 시 반환 받는 데이터에 "isMyFeed" 데이터 추가
- "삭제하기" 기능의 UI 출력 여부를 판단하기 위한 데이터가 필요하여 추가하기 위해 코드 수정
- 코드 로직에 문제가 없는지 확인 부탁드립니다.
fixed #329
> fix: 냥이생활 피드 반환 데이터에 isMyFeed 데이터 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedMultiResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserCatResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowFeedGetDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowGetResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowerResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/follow/FollowingResponseDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/FollowMapper.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
- 냥이생활 피드 작성 페이지에 사용될 로그인 된 유저의 고양이 프로필 조회 API에 사용될 응답 Dto 생성
- Mapper에 cat 리스트를 응답 dto로 변환하는 메서드 생성
- user/dto 패키지내 follow 패키지 생성하여 follow 관련 dto 분리
- UserController에 CatService 주입하여 findCatsByUser 메서드 호출
- UserController에 getCats 구현
- user 패키지 내 dto가 많아져 follow 패키지 생성하여 리팩토링 하였습니다.
- 냥이생활 피드 작성 시 로그인된 유저 정보를 이용해 모든 고양이 프로필의 id, name, profileImage를 반환하는 API를 생성했습니다.
- 로직 상 틀린 부분은 없는지
- 오타가 없는지
- close #319
> feat: 냥이생활 피드 작성 시 로그인된 유저의 모든 고양이 프로필 정보를 받아오는 API 구현

- client/src/pages/Feed/Feeds/Feeds.tsx
- client/src/redux/store/index.ts
- 로그인 여부를 체크하는 로직이 포함된 ``handleLikeClick`` 함수를 리팩토링했습니다.
- 기존의 코드는 ``if...else``문이 중첩되어 코드의 가독성이 떨어진다고 판단했습니다.
- 따라서 ``Early Return``을 사용해 코드의 가독성을 높이고 명시적으로 리팩토링했습니다.
- ``redux-persist``를 도입해 ``isLogin`` 상태를 사용한 이후로 아래와 같은 에러가 발생하면서 빌드에 실패합니다.
> Property 'isLogin' does not exist on type 'unknown'.
- 에러가 발생하는 파일 모두 ``isLogin`` 상태를 사용한다는 공통점이 있습니다.
- 따라서 ``redux-persist``를 적용하는 과정에서 타입과 관련된 에러가 발생했다고 생각했습니다.
- 문제 해결을 위해 구글링하던 중, 비슷한 타입 이슈를 발견했습니다.
[출처: redux-persist on typescript #1140](https://github.com/rt2zz/redux-persist/issues/1140)
- 따라서 ``persistedReducer``에  ``RootState`` 라는 타입을 지정해보았습니다.
- 만약 이후에도 빌드에 실패하면 다시 원인과 해결 방안을 모색하겠습니다.
#332 
[[클린코드 JS] Else if와 Else를 피하고 Early Return하자](https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED% …
> [FE] isLogin 상태 타입 에러에 해결 방법 적용

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
- 집사생활 검색 기능 추가
- title, body, user name으로 검색 가능
- all, tag는 이후 추가 필요
- 집사생활에 등록된 게시글의 검색 기능을 추가하기 위해 변경
- all은 주석을 풀 경우 에러 발생
- title, body, user name에 대한 검색 로직
resolved #270
> feat: 집사생활 검색 기능 추가

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeRepository.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeService.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
- FeedController에 `냥이생활/users/{users-id}/likes` 엔드포인트로 갖는 특정 유저가 좋아요 누른 냥이생활 피드를 모두 조회하는 API 구현
- 페이지네이션 적용 (MultiResponseDto 사용)
- param 기본값으로 page = 1, size = 10
- FeedController.getFeedFromUserLike() -> FeedService.findFeedByLike() -> LikeService.findLikeByUserLike() -> LikeRepository.findByUserAndFeedIsNotNull() 호출
- 유저가 좋아요를 누른 데이터가 많아지는 상황을 고려하여 페이지네이션을 적용했습니다.
- 조회할 때 Like 테이블에서 조회하므로 likeId descending으로 정렬하여 반환 (최신순)
- 좋아요 정보는 Like 테이블에 있기 때문에 서비스 단에서 like service를 호출하여 조회합니다.
- LikeRepository에서 `feed` 가 `not null` 이면서 파라미터로 전달된 `user` 와 일치하는 데이터를 page로 반환하도록 구현
- page의 내용물이 `like` 이므로 like 안의 `feed` 로 변환합니다.
- postman을 통한 테스트 통과했습니다.
- 엔드포인트가 적절한지
- 메서드 명이 적절한지
- 잘못된 로직이 없는지
- close #293
> feat: 특정 유저가 좋아요 누른 냥이생활 피드 조회 API 구현(페이지네이션 적용)

- client/src/components/modules/Header/Header.style.ts
- client/src/components/modules/Header/Header.tsx
- client/src/components/modules/Header/index.ts
- client/src/components/template/PostForm/PostForm.style.tsx
- client/src/components/template/PostForm/PostForm.tsx
- client/src/layout/MainLayout.tsx
- client/src/pages/Board/Boards/Boards.style.tsx
- client/src/pages/Board/NewBoard/NewBoard.style.ts
- client/src/pages/Board/NewBoard/NewBoard.tsx
- client/src/pages/Feed/NewFeed/NewFeed.style.ts
- client/src/pages/Feed/NewFeed/NewFeed.tsx
- client/src/pages/Profile/Profile.tsx
- client/src/routes/AppRoutes.tsx
1. Header Component를 분리하여 src/components/modules/Header/Header.tsx에서 관리합니다.
1. Header Component를 분리하여 src/components/modules/Header/Header.tsx에서 관리합니다.
```jsx
// 기본적인 사용 방법
<Header>집사생활 글쓰기</Header>
```
```jsx
// 좌측의 뒤로가기 버튼 사용하고 싶지 않을 때
<Header backButtonDisabled>
버튼 없는 헤더
</Header>
```
```jsx
// 우측에 추가로 버튼을 위치시키고 싶을 때
<Header>
집사생활 글쓰기
<Button/>
</Header>
```
- 그에 따라 Profile.tsx, NewBoard,tsx, NewFeed.tsx를 수정하였습니다.
- Header의 `position: fixed`를 사용하여 항상 뷰포트 상단에 위치합니다
- Header는 항상 뷰포트를 기준으로 움직이므로 발표용 레이아웃과 함께 사용할 수 없습니다. 따라서 필요없어진 발표용 레이아웃을 제거하였습니다.
- 
[client/src/components/modules/Header/Header.style.ts](https://github.com/codestates-seb/seb39_main_059/pull/349/files#diff-b213896e22d9719b44a36ff19bc14bf7d8c9f6a9c7a5662861ee019d8eead20f)
> refactor: header component 분리 제작

- client/src/components/modules/Dropdown/Dropdown.tsx
- client/src/components/template/FeedDetail/FeedDetail.tsx
- 냥이생활 피드 삭제 기능을 구현했습니다.
- 드롭다운의 ``'삭제하기'``에 ``handleDeleteFeed`` 함수를 전달해 사용자가 클릭하면 해당 함수가 실행됩니다.
- 삭제 로직과 에러 핸들링이 올바른지, 더 나은 방법이 있는지 확인부탁드립니다.
#97
> [FE] 냥이생활 피드 삭제 기능 구현

- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/SecurityConfig.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/TokenDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/TokenRequestDto.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/provider/JwtTokenizer.java
- server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/service/AuthService.java
- SecurityConfig에 /reissue 요청 시(모든 http 메서드) 인증 절차 거치지 않도록 코드 추가(permitAll)
- TokenRequestDto에 accessToken 변수 삭제 및 TokenDto에 request 로 사용할 수 있도록 애너테이션 추가
- jwt 토큰 header에 type 정보 추가 및 reissue 요청시 type 검증 로직 추가
- reissue 요청시 request body에 refreshToken만 받도록 수정
- authService에 reissue 로직에서 기존에 accessToken을 받아 인증정보를 가져오던 것을 아래와 같은 순서로 로직 변경
refreshToken에서 userName을 꺼냄 -> userName으로 UserDetails를 불러옴 -> UserDetails로 authentication 정보 생성 -> 토큰 재발급
- login(토큰 생성), reissue(토큰 재발급) 요청 모두 정상 작동하는지 postman으로 테스트 완료 했습니다.
- reissue 요청시 request body에 accessToken과 refreshToken을 모두 받던 것을 만료된 엑세스 토큰을 전달하는 것이 적절하지 않다는 @leejuhanKr  의 의견으로 refreshToken만 받도록 api 수정하였습니다.
- 리프레쉬 토큰을 이용하여 만료된 토큰 재발급 요청 시 액세스 토큰은 만료된 상태이기 때문에 인증 filter를 거치면 401 에러가 발생할 수 있어 인증 필터를 거치지 않도록 수정했습니다.
- TokenRequestDto와 TokenDto 내부 …
> fix: reissue request body에 accessToken 안받도록 API 변경

- client/src/pages/Feed/NewFeed/NewFeed.tsx
- client/src/redux/actions/FeedDetailAction.ts
- 냥이생활 피드 작성 기능을 추가했습니다.
- 냥이생활은 유저의 고양이 프로필로 작성하기 때문에, 고양이 정보를 불러오는 API를 호출합니다.
- 고양이 프로필이 등록되어있지 않은 유저일 경우 고양이 등록 페이지로 이동하는 알림창을 띄웁니다.
- 고양이 프로필을 선택하는 컴포넌트 (select)를 분리하지 않았습니다.
- 기능 머지 이후 컴포넌트 분리 및 css를 작업할 예정입니다.
#137
> [FE] 냥이생활 피드 작성 기능 추가

- client/src/api/auth.ts
- client/src/utils/instance.ts
- client/src/utils/tokenControl.ts
인증이 필요한 요청에 axiosInstance가 대응할 수 있도록 하였습니다.
이제 헤더에 `tokenNeeded: true`를 설정하면 access token이 header에 담겨 요청됩니다.
access token이 만료되었다면 refresh 토큰을 통해 최신화 시켜준 후 요청을 전송합니다.
기존에 인증이 필요한 요청시 일일이 token을 설정해야하는 불편함이 있었습니다.
이를 해결하기 위해 axiosIstance에 로직을 추가해 주었습니다.
``` jsx
async function authorizationSetter(config: AxiosRequestConfig) {
// 헤더에 tokenNeed라는 속성이 있는지 확인
const header = config.headers!
// tokenNeed라는 속성이 없다면 그대로 config 반환
if (!header?.tokenNeeded) return config
// 있다면 accessToken을 가져옴
let accessToken = retrieveUserToken('ACCESS_TOKEN')
if (!accessToken) {
// 에러 핸들링
}
//  accessToken 만료시 refreshToken을 사용하여 재발급
if (isTokenExpired(accessToken)) {
const refreshToken = retrieveUserToken('ACCESS_TOKEN')
const renewedAccessToken = await renewAccessToken(refreshToken!)
if (!renewedAccessToken) { …
```
> Feat: axios auth instance 생성
