server/catvillage/src/main/java/com/twentyfour_seven/catvillage/utils/CustomBeanUtils.java

- patch 동작에 사용시 편리한 유틸 클래스 추가
- patch(수정) 동작에 사용하여 쉽게 동작을 구현할 수 있게끔 도와주는 유틸 클래스 추가
- CustomBeanUtils class
resolved #32

feat: custom bean utils 추가

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/BusinessLogicException.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java

- 예외 처리용 클래스 구현
- 앞으로 필요한 예외는 Enum에 추가를 하여 사용
- 예외 발생 필요 시 추가해야 할 예외를 한 곳에 모아서 관리하기 위해 작성
- BusinessLogicException class
- ExceptionCode class
resolved #33

feat: global exception 처리 클래스 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/UserRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java

- user 도메인의 필수 클래스 구조 구현
- controller 및 service, dto 등 상세 구현 필요
- user 도메인 개발 시 필요한 패키지 별 구조 작성
- entity 제외 틀만 잡아둔 상태이므로 상세 구현 필요
- entity 또한 연관관계에 대한 내용은 구현하지 않았으므로 이후 추가 필요
- Controller 클래스에 Transactional 어노테이션 적용
- User class
resolved #6

feat: user 필수 클래스 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPostDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserPostResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/repository/UserRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java

- 일반 회원가입 기능 추가
- 이름 중복 검사 기능 추가
- 일반 회원가입 기능을 추가함으로써 필요한 post dto, response dto 추가
- post dto에는 validation 옵션 적용
- 기존에 임시로 만들어 두었던 예외 코드 수정 및 추가
- 유저 RestAPI의 각 응답별로 유저 ID가 누락되어 있었기에 추가
- UserController class의 RestAPI method
- UserPostDto class
- UserPostResponseDto class
- UserMapper interface
- UserService class
solved #9, solved #11

feat: 일반 회원가입 및 이름 중복 검사 기능 구현

---

client/src/@types/styled.d.ts
client/src/App.tsx
client/src/styles/GlobalStyle.ts
client/src/styles/Iphone11ProContainer.tsx
client/src/styles/theme.ts

- 자주 사용하는 스타일 속성을 변수명으로 사용하기 위해 theme을 생성했습니다.
- typescript에서 theme을 사용하기 위해 styled.d.ts 파일에 type을 선언해주었습니다.
- theme을 App 컴포넌트에 적용해 하위 컴포넌트에서도 theme에 접근해 변수명을 사용할 수 있도록 했습니다.
- 기존의 ``height: 100vh``으로 했을 때 컨테이너가 제대로 정렬되지 않거나 border가 잘리는 현상을 발견했습니다.
- css의 내장 함수인 ``max()``를 사용해 해결했습니다.
- 또한 텍스트가 컨테이너 밖으로 넘치는 현상을 발견했습니다.
- ``overflow: scroll``로 해당 문제를 해결하고, 스크롤바가 보이지 않도록 하는 속성을 추가했습니다.
[Styled-Components TypeScript](https://styled-components.com/docs/api#typescript)
[CSS 함수 - min(), max()](https://www.daleseo.com/css-min-max/)

style: 공통 스타일 속성 관리를 위한 theme 설정

---

.github/workflows/auto-build.yml
appspec.yml
scripts/deploy.sh

- appspec.yml 생성
- deploy.sh 스크립트 생성
- auto-build.yml Code Deploy 명령 추가
- 배포 자동화를 위한 수정
- appspec.yml
- deploy.sh
- auto-build.yml

chore: 배포 자동화 설정 파일 생성

---

.github/workflows/client-auto-deploy.yml

배포 자동화 설정을 위해 auto-deploy.yml 파일을 생성했습니다.
배포 자동화를 위해 PR이 생성되고 close될때 ./client가 변경 되었다면 action이 트리거 되게 하였습니다.
[.github/workflows/client-auto-deploy.yml](https://github.com/codestates-seb/seb39_main_059/pull/102/files#diff-4f31bdffdfeae050984cac67d939d1190da3a8edd770f034d76e29369e97a1c9)

feat: 배포 자동화 설정 파일 생성

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/Board.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/repository/BoardRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/service/BoardService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java

- Board(집사생활) 필수 클래스 생성
- Board(집사생활) 구현을 위한 필수 클래스 및 인터페이스 생성
- Controller, dto, mapper, entity, repository, service 생성
- BoardPostDto class
- BoardPostResponseDto class
- Board class
resolved #104

feat: 집사생활 필수 클래스 생성

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/TagToCatId.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/repository/TagToCatRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/controller/FeedController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/dto/FeedResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedTag.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/TagToFeed.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/TagToFeedId.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/mapper/FeedMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedCommentRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/FeedTagRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/repository/TagToFeedRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedCommentService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/service/FeedTagService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java

- Feed, FeedComment, FeedTag, TagToFeed, TagToFeedId(복수 id를 위한 클래스) 작성
- Picture와 Feed 양방향 연관관계 매핑 적용
- User와 Feed, FeedComment에 양방향 매핑 적용
- TagToCat에 복합키 관련 설정 변경
- 냥이생활에 필요한 필수 클래스를 생성하였습니다.
- TagToCatRepository에 Id가 long타입으로 되어있어 복합키 사용하므로 복합키 클래스로 변경하였습니다.
- 양방향 매핑 잘못 작성된 부분 없는지
- User
- TagToCatId
- TagToCatRepository
#93

feat: 냥이생활(Feed) 필수 클래스 생성

---

client/src/pages/Signup/Signup.style.ts
client/src/pages/Signup/Signup.tsx
client/src/pages/Signup/index.ts

- 회원가입 화면을 마크업했습니다.
- 로그인 화면과 마찬가지로 '비밀번호 보기'를 위한 checkbox를 생성했습니다.
- 유효성 검사와 같은 로직은 아직 구현되어 있지 않습니다.
#116

feat: 회원가입 화면 마크업

---

client/src/components/atoms/ContentInput/ContentInput.style.tsx
client/src/components/atoms/ContentInput/ContentInput.tsx
client/src/components/atoms/ContentInput/inedx.ts

ContentInput 마크업
글 생성 페이지의 제목, 내용을 입력하고 보여주는 영역을 textrea 태그를 사용하여 만들었습니다.
글 생성에서 글제목, 글내용 부분에 사용할 수 있습니다.

feat: ContentInput 마크업

---

.github/workflows/PR-build.yml
server/catvillage/build.gradle
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/controller/FileUploadController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/dto/PictureDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/entity/Picture.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/picture/service/S3UploadService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/aws/AwsConfig.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java
server/catvillage/src/main/resources/application.yml

- aws 에서 지원하는 sdk를 사용하기 위한 의존성 추가(build.gradle)
- aws에 파일 업로드를 위한 설정 코드 추가(application.yml, AwsConfig)
- upload 요청을 받기 위한 Controller를 picture 패키지에 추가(FileUploadController)
- upload 요청을 처리하기 위한 Service를 picture 패키지에 추가(S3UploadService)
- aws 에 파일(이미지) 업로드를 자동으로 하기 위해 코드를 추가하였습니다.
- 서버로 upload 요청 시 자동으로 S3에 지정한 경로로 저장됩니다.
- applicaton.yml
- build.gradle
- AwsConfig
- FileUploadController
- S3UploadService
- secret 때문에 PR 빌드 실패 할 수 있어 빌드 실패하면 workflow 설정 파일 코드 수정 필요합니다!

feat: spring에 S3로 파일 업로드 코드 구현

---

client/package-lock.json
client/package.json
client/src/components/atoms/Input/Input.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/Signup.style.ts
client/src/pages/Signup/Signup.tsx

- React Hook Form 이라는 라이브러리로 회원가입 정보 입력에 필요한 유효성 검사를 구현했습니다.
- 이메일, 비밀번호, 비밀번호 확인 세 가지를 검사하고, 유효성 검사를 모두 통과한 경우에만 양식 제출이 가능하도록 했습니다.
- React Hook Form 라이브러리는 input 요소에 ref를 전달하므로 ref를 props로 받을 수 있어야 합니다.
- 하지만 기존의 Input 컴포넌트는 ref를 props로 전달받지 않습니다.
- 따라서 forwardRef를 사용해 기존의 Input 컴포넌트가 ref를 받을 수 있도록 했습니다.
```ts
// src/components/atoms/Input/Input.tsx
// 컴포넌트 전체를 forwardRef로 감싸서 ref를 props로 전달받을 수 있습니다.
const Input: FC<Props> = forwardRef(({ inputName, ...props }, ref) => {
return <S.Input name={inputName} {...props} ref={ref} autoComplete="off" />
})
```
- 기존에 작성한 코드에서는``회원 가입`` 버튼 이외에도 양식 제출과는 관련 없는 코드까지 form 요소 내부에 있었습니다.
- 따라서 form과는 관련 없는 코드의 위치를 form 요소의 외부로 바꿨습니다.
- form 내부에서 작성한 정보가 주소창에 그대로 표시되는 현상을 발견했습니다.
- method 속성을 post로 설정하면 표시되지 않기 때문에 form 요소에 ``method="post"``를 추가했습니다.
- …

feat: 회원가입 유효성 검사 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/CustomOAuth2UserService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/dto/UserMyInfoDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java

- UserController에 /my-info 요청 받기 위한 getMyInfo 메서드 생성
- userService의 findVerifiedEmail 호출
- 응답 객체인 UserMyInfoDto 구현
- 리팩토링
- 로그인 후 유저 기본 정보를 가져오는 api가 필요하여 생성하였습니다.
- findVerifiedEmail에서 유저 정보가 DB에 있는지 확인하므로 검증하는 로직 추가로 작성하진 않았습니다.
- 리팩토링 했습니다.(안 쓰는 import 문 제거, 코드 사이 공백 정리)
- 엔드포인트가 올바른지
- 오타는 없는지
- 로직이 잘못되지 않았는지
- close #189

feat: 로그인 후 유저 기본정보 가져오는 API 구현

---

client/src/@types/user.ts
client/src/pages/Login/Login.tsx
client/src/redux/actions/userAction.ts
client/src/redux/reducers/userSlice.ts

- 일반 로그인 기능을 구현했습니다.
- 로그인에 성공하면 냥이생활 전체 피드 페이지로 리다이렉트 되도록 했습니다.
- 서버와 통신 이후 에러 핸들링할 예정입니다!
#119

feat: 일반 로그인 기능 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/config/CorsConfig.java

- CORS 에러 수정을 위한 allowed origin 수정
- CORS 에러가 발생하지 않도록 allowed origin을 수정

fix: allowed origin 수정

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/controller/AuthController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/security/dto/UserRequestDto.java

- UserRequestDto에 username을 email로 변경
- client에서 로그인 요청시 Id로 email 변수 전달되도록 구현되어 있어서 수정했습니다.
- AuthController는 자동 줄 정렬 단축키 사용하여 들여쓰기만 변경된거라 코드상 변화는 없습니다. 😄
- UserRequestDto

fix: 로그인 시 입력정보 username에서 email로 변경

---

client/src/components/modules/TabBar/TabBar.style.ts

style: 세부 css 스타일 조정

---

client/src/components/modules/TabBar/TabBar.tsx
client/src/layout/MainLayout.tsx

fix: 임시 tabbar를 modules에 정의한 tabbar로 교체

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/controller/UserController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/service/UserService.java

- 유저 정보 변경 및 탈퇴 시 로그인 유저의 정보를 기반으로 동작하도록 로직 변경
- 두 API의 endpoint에서 ID 값 입력 부분 제거
- 비밀번호 변경 시 암호화하여 저장하도록 로직 수정
- 로그인 유저 정보를 알 수 있기 때문에 이에 맞춰 로직 수정
- 정보 변경 및 탈퇴 시 로그인 유저 정보 기반으로 동작하기 때문에 유저 검증 로직은 제외
- 회원 탈퇴 로직을 DB에서 바로 제거가 아닌 Role 변경 및 expiryDate 설정으로 변경
- 비밀번호 변경 시 평문으로 저장되던 부분을 암호화 하도록 수정
- UserController class
- UserService class
fixed #142
fixed #150
fixed #194

fix: 유저 정보 변경 및 탈퇴 기능 수정

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/controller/BoardController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPatchDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/dto/BoardPostResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/mapper/BoardMapper.java

- 집사생활 request body에 사용되는 dto에서 잘 못 된 필드명 수정
- controller에서 사용한 getter, setter도 맞춰서 수정
- request body에 사용되는 키 값과 DTO에 사용되는 필드명이 달라서 mapping이 안되던 문제가 발생하여 해당 부분 수정

fix: 집사생활 request body 수정

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/entity/Cat.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/controller/CatInfoController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoGetResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoPostDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/dto/CatInfoResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/CatInfo.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/Disease.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/DiseaseToCat.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/entity/DiseaseToCatId.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/mapper/CatInfoMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/repository/CatInfoRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/repository/DiseaseRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/repository/DiseaseToCatRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/catInfo/service/CatInfoService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java

- catInfo 패키지 내에 CatInfo, Disease, DiseaseToCat 관련 클래스 구현
- CatInfoController에 등록하기 기능 구현
- CatInfoService에 등록하기 기능 구현, 한국어 이름으로 중복되는 고양이 품종이 있는지 검사하는 기능 구현
- 고양이 품종 정보에 필요한 필수 클래스 및 인터페이스 생성했습니다.
- 시간관계상 고양이 품종정보 페이지는 집사생활에 게시글 형식으로 올릴 예정이라 등록하기를 제외한 기능 개발은 잠시 멈췄습니다.
- 나중에 기능을 만들때 활용하기 위해 작성한 코드는 올려두려 합니다.
- 연관관계 매핑이 올바르게 되어있는지
close #205

feat: 고양이 품종정보 필수 클래스 구현 및 등록하기 기능 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/Board.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/board/entity/BoardComment.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/Like.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeRepository.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/common/like/LikeService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/Feed.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/feed/entity/FeedComment.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/entity/User.java

- Like entity, repository, service 구현
- 좋아요에 필요한 메서드 LikeService에 작성
- Like와 user, feed, board, feedComment, boardComment 양방향 매핑 적용
- 좋아요 기능을 위해 필수 클래스 구현했습니다.
- 엔티티간 양방향 매핑 올바르게 되었는지
- LikeService
close #200

feat: like 필수 클래스 구현 및 서비스 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java

- 회원가입 시 프로필 이미지를 올리지 않을 경우, 기본 프로필 이미지가 적용 되도록 로직 수정
- 기본 프로필 이미지가 적용 될 수 있도록 로직 수정
fixed #245

fix: 기본 프로필 이미지 적용

---

client/src/@types/feed.ts
client/src/components/template/FeedDetail/FeedDetail.tsx
client/src/pages/Feed/FeedDetail/FeedDetail.tsx
client/src/pages/Feed/Feeds/Feeds.tsx
client/src/redux/actions/FeedDetailAction.ts
client/src/redux/reducers/FeedDetailSlice.ts
client/src/redux/reducers/FeedsSlice.ts
client/src/redux/store/index.ts

- 냥이생활 전체 피드에서 게시물을 클릭하면 특정 피드의 페이지로 이동합니다.
- ``react-router-dom``의 ``Link`` 컴포넌트를 사용했습니다.
```tsx
// client/src/pages/Feed/Feeds/Feeds.tsx
feed.map(item => {
return (
<Link to={`/${FEED_PATH}/${item.feedId}`} key={item.feedId}>
<S.FeedItem>
<Image src={item.image} />
<SvgButton icon="HeartIcon" cssProp={SvgButtonCssProp} />
</S.FeedItem>
</Link>
)
})}
```
- 특정 피드의 ``feedId``값을 이용해 서버에 해당 id값을 가진 피드 데이터를 요청하는 로직을 구현했습니다.
- 이를 위해 FeedDetailAction.ts에 getFeedDetailAsync 함수를 정의했습니다.
```tsx
// client/src/redux/actions/FeedDetailAction.ts
// 서버에 특정 피드의 데이터를 요청하는 함수
export const getFeedDetailAsync = createAsyncThunk<
FeedDetail,
string,
CreateAsyncThunkTypes
>('feedDetail/getFeedDetailAsync', async (payload, thunkAPI) => {
try {
const { data } = await …
```

[FE] 냥이생활 특정 피드 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/user/mapper/UserMapper.java

- profile image 미입력 시 null pointer exception 발생 부분 수정
- null pointer exception을 해결하기 위해 null 체크부터 진행하도록 수정
fixed #252

fix: 회원가입 시 null pointer exception 해결

---

client/src/components/atoms/Comment/Comment.style.ts
client/src/components/atoms/Comment/Comment.tsx
client/src/components/template/Comments/Comments.style.tsx
client/src/components/template/Comments/index.ts
client/src/components/template/FeedDetail/FeedDetail.style.tsx
client/src/components/template/FeedDetail/FeedDetail.tsx

- 냥이생활 및 집사생활 게시판에서 사용되는 댓글 컴포넌트의 스타일링을 수정했습니다.
- 댓글 템플릿을 생성했습니다.
- 기존의 댓글 컴포넌트에서 댓글 내용이 길어지면 프로필 영역이 줄어드는 현상을 발견했습니다.
- 댓글에서 프로필/댓글 내용/좋아요 버튼을 각각의 독립된 부모 컨테이너로 감쌌습니다.
- 또한 댓글이 스크롤되도록 했습니다.

feat: 댓글 컴포넌트 수정 밎 댓글 템플릿 생성

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/controller/CatController.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/dto/CatUserResponseDto.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/mapper/CatMapper.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/cat/service/CatService.java
server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java

- CatController에 getCatFromUser 메서드추가
- 응답 dto로 사용할 CatUserResponseDto 구현, Swagger에 추가 
- 유저 프로필 페이지에 고양이 정보가 들어가 API 추가했습니다.
- 응답 데이터가 올바른지
- 로직이 잘못되지 않았는지
close #273

feat: 유저 ID로 고양이 정보 불러오는 API 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/config/SwaggerConfig.java

- SwaggerConfig 수정
- 사용하지 않는 객체  제거
- 불필요한 인증 파라미터 정보 제거(AuthenticationPrincipal 사용하면서 발생)
- SwaggerConfig

fix: SwaggerConfig 수정

---

client/src/@types/board.ts
client/src/components/modules/TabBar/TabBar.style.ts
client/src/data/index.ts
client/src/layout/MainLayout.tsx
client/src/pages/Board/Boards/BoardView.style.tsx
client/src/pages/Board/Boards/BoardView.tsx
client/src/pages/Board/Boards/Boards.style.tsx
client/src/pages/Board/Boards/Boards.tsx
client/src/pages/Board/Boards/BreedSelection.style.tsx
client/src/pages/Board/Boards/BreedSelection.tsx
client/src/pages/Board/Boards/Tab.style.tsx
client/src/pages/Board/Boards/Tab.tsx
client/src/redux/actions/boardsAction.ts
client/src/redux/reducers/BoardsSlice.ts
client/src/redux/store/index.ts

집사생활 게시글 모아보기 페이지를 작성하였습니다.
집사생활 게시글 모아보기 페이지를 작성하고 관련로직들을 작성하였습니다.

Feat: 집사생활 게시글 모아보기 페이지 작성

---

client/src/@types/feed.ts
client/src/components/modules/ImageInput/ImageInput.style.tsx
client/src/components/template/FeedDetail/FeedDetail.style.tsx
client/src/components/template/FeedDetail/FeedDetail.tsx
client/src/components/template/FeedForm/FeedForm.style.tsx
client/src/pages/Feed/Feeds/Feeds.tsx
client/src/pages/Feed/NewFeed/NewFeed.tsx

- 로그인하지 않은 유저가 로그인이 필요한 서비스에 접근할 경우 리다이렉트되도록 구현했습니다.
- 냥이생활 전체 피드와 냥이 생활 상세 피드 페이지의 스타일 관련 코드를 수정했습니다.
- 그 외에도 Feed 타입의 like가 isLike로 변경됨에 따라 필드명을 수정했습니다.
- 냥이생활의 컴포넌트 스타일링 코드에 문제가 생겨 이전 코드가 제대로 빌드되지 않았습니다.
- 수정 이후에도 빌드에 실패할 경우 다시 확인하겠습니다.

fix: 냥이생활 관련 수정

---

client/src/components/template/FeedForm/FeedForm.tsx
client/src/pages/Feed/Feeds/Feeds.tsx
client/src/redux/reducers/FeedsSlice.ts

- 냥이생활 전체 피드에서 좋아요 기능을 구현했습니다.
- 로그인되어 있는 유저가 좋아요 버튼을 클릭할 경우 좋아요 버튼이 활성화됩니다.
- 로그인되어 있지 않은 유저가 클릭할 경우 로그인 페이지로 리다이렉트합니다.

feat: 냥이생활 전체 피드 좋아요 구현

---

server/catvillage/src/main/java/com/twentyfour_seven/catvillage/exception/ExceptionCode.java

- ExceptionCode에 INVALID_USER 부분 에러코드 405(Method not allowed)에서 401(User not granted)로 수정
- INVALID_USER(로그인한 유저가 해당 요청에 요청이 가능한 유저가 아닐 경우 발생하는 오류) 에서 에러 코드가 405(Method not allowed)로 되어 있어 에러가 적절하지 않아 에러 핸들링에 어려움이 있기 때문에 수정했습니다.
- 에러코드, 에러 메시지 적절한지
- close #311

fix: Exception 에러 코드 수정

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/index.tsx
client/src/pages/Feed/Feeds/Feeds.tsx
client/src/pages/Feed/NewFeed/NewFeed.tsx
client/src/redux/reducers/FeedsSlice.ts
client/src/redux/store/index.ts

- 새로고침할 때 ``store``가 초기화되는 문제를 해결하기 위해 ``redux-persist``를 도입했습니다.
- ``redux-persist``의 설정을 추가했습니다.
```ts
// client/src/redux/store/index.ts
// 1. persist 설정을 정의하는 객체
const persistConfig = {
key: 'root',
version: 1,
storage,
// whitelist 속성으로 원하는 reducer만을 persist로 관리할 수 있습니다.
// 로그인 상태인 isLogin state를 사용할 것이기 때문에 user 리듀서를 추가했습니다.
whitelist: ['user'],
}
// 2. config 객체를 적용한 reducer를 반환하는 persistedReducer를 생성합니다.
const persistedReducer = persistReducer(persistConfig, rootReducer)
// 3. persist의 config가 적용된 persistedReducer를 적용해 스토어를 생성합니다.
export const setupStore = (preloadedState?: PreloadedState<RootState>) => {
return configureStore({
reducer: persistedReducer,
preloadedState,
// 에러 해결 과정에서 추가한 미들웨어 설정입니다.
middleware: getDefaultMiddleware =>
getDefaultMiddleware({
serializableCheck: …
```

[FE] 로그인 상태 유지 기능 구현

---

client/src/api/auth.ts
client/src/components/template/FeedDetail/FeedDetail.tsx
client/src/components/template/PostForm/PostForm.tsx
client/src/pages/Board/NewBoard/NewBoard.tsx
client/src/pages/Cat/Cat.tsx
client/src/pages/Feed/NewFeed/NewFeed.tsx
client/src/redux/actions/FeedDetailAction.ts
client/src/redux/actions/FeedsAction.ts
client/src/redux/actions/boardsAction.ts
client/src/redux/actions/userAction.ts
client/src/utils/instance.ts
client/src/utils/tokenControl.ts

axiosInstance에서 header의 설정 사항들을 바꿔주었습니다.
```js
// 기존
Authorizaion: `Bearer ${accessToken}`
// 최신
tokenNeeded: true
```
이전 작업(#355)에서 axios-instance의 헤더에 `tokenNeeded: true`를 추가하면 유요한 access 토큰을 `Authorizaion`에 추가하도록 하였습니다.
이에 따라 위의 수정사항과 관련되 파일들에 대해서도 리팩토링을 진행해 주었습니다.
#355

Refactor: axios instance
